---
title: "Syllabus"
author: "Florian Oswald, Gustave Kenedi, Pierre Villedieu"
date: "1/28/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

The material below is a complement to the lecture slides and should be used as reference. Readings in **bold** are **very highly** recommended.


#### Lecture 1: Introduction

[**1.1 and 1.2, Introduction to Econometrics with R**](https://scpoecon.github.io/ScPoEconometrics/R-intro.html)

**Introduction, Mastering Metrics**

[**Angrist and Pischke (2010 JEP), *The Credibility Revolution in Empirical Economics***](https://www.aeaweb.org/articles?id=10.1257/jep.24.2.3)  

<br>

#### Lecture 2/3: Data Visualization and Data Wrangling

[**Chapter 2, Introduction to Econometrics with R**](https://scpoecon.github.io/ScPoEconometrics/sum.html)

[**Schwabish (2014 JEP), An Economist's Guide to Visualizing Data**](https://www.aeaweb.org/articles?id=10.1257/jep.28.1.209)

Chapters [2](https://moderndive.com/2-viz.html) and [3](https://moderndive.com/3-wrangling.html), ModernDive

<br>

#### Lecture 4: Simple Linear Regression

[**Chapter 3, Introduction to Econometrics with R**](https://scpoecon.github.io/ScPoEconometrics/linreg.html)

**Chapter 2, Mastering Metrics (pp. x-y)**

[Chapter 5, ModernDive](https://moderndive.com/5-regression.html)

<br>

#### Lecture 5: Introduction to Causality

[**Chapter 7, Introduction to Econometrics with R**](https://scpoecon.github.io/ScPoEconometrics/causality.html)

**Chapter 1, Mastering Metrics**

[Deaton and Cartwright (2016, VoxEU), "The limitations of randomised controlled trials"](https://voxeu.org/article/limitations-randomised-controlled-trials)

<br>

#### Lecture 6: Multiple Linear Regression

[**Chapter 4, Introduction to Econometrics with R**](https://scpoecon.github.io/ScPoEconometrics/multiple-reg.html)

**Chapter 2, Mastering Metrics (pp. x-y)**

[Chapter 6, ModernDive](https://moderndive.com/6-multiple-regression.html)

<br>

#### Lecture 7: Sampling

[**Chapter 7, ModernDive**](https://moderndive.com/7-sampling.html)

<br>

#### Lecture 8/9: Statistical Inference and Hypothesis Testing

**Chapters [8](https://moderndive.com/8-confidence-intervals.html), [9](https://moderndive.com/9-hypothesis-testing.html) and [10](https://moderndive.com/10-inference-for-regression.html), ModernDive**

<br>

#### Lecture 10: Difference-in-Differences

**Chapter 5, Mastering Metrics**

[**Card and Krueger (1994 AER), "Minimum Wages and Employment: A Case Study of the Fast-Food Industry in New Jersey and Pennsylvania"**](http://davidcard.berkeley.edu/papers/njmin-aer.pdf)

<br>

#### Lecture 11: Regression Discontinuity

**Chapter 4, Mastering Metrics**

[**Carpenter and Dobkin (2009, AEJ: Applied), "The Effect of Alcohol Consumption on Mortality: Regression Discontinuity Evidence from the Minimum Drinking Age"**](https://www.aeaweb.org/articles?id=10.1257/app.1.1.164)

*Literature reviews:*  
[Imbens and Lemieux (2008 JMetrics), "Regression discontinuity designs: A guide to practice"](https://faculty.smu.edu/millimet/classes/eco7377/papers/imbens%20lemieux%202008.pdf)

[Lee and Lemieux (2010 JEL), "Regression Discontinuity Designs in Economics"](Regression Discontinuity Designs
in Economics)

<br>

#### Lecture 12: Review Session

